### ISSUE TITLE
WorldMapState

### ISSUE THREAD

**Issue by alexeevdv** [falltergeist/falltergeist#144]
Реализовать карту мира:
- Отрисовка интерфейса карты
- Отрисовка фона карты
- Отрисовка списка городов(сами города на карте рисовать не надо. Принимаем за данность что все города нам известны, т.е. выводим полный список)
- Отрисовка положения персонажа(просто крестик. анимацию движения не делать)
- При клике на фоне карты перемещать в это место крестик персонажа и скролить соответствующим образом фон карты

**Comment by phobos2077** [comment]
Replaced by #392 and #393
