### ISSUE TITLE
Renderer doesn't use ResourceManager while loading egg texture

### ISSUE THREAD

**Issue by isage** [falltergeist/falltergeist#249]
Renderer always looks for egg in data/egg.png.
Should use ResourceManager

**Comment by isage** [comment]
http://stackoverflow.com/questions/2058141/reading-sdl-rwops-from-a-stdistream
example wrapper for RWops around iostream
Note that we are using streambuf's.

**Comment by alexeevdv** [comment]
I don't see why we should use RWops. Looks like streambuf provides the same functionality. Is there real profit in RWops usage?

**Comment by isage** [comment]
SDL_image can't load from streambuf. (can from a memory, though. maybe i'll use that)

**Comment by alexeevdv** [comment]
I am thinking about DataProvider interface for ResourceManager. So we can use different methods and places for data search. Something like plugins system. We can implement DATfiles plugin or Memory plugin. What do you think?

**Comment by isage** [comment]
Yeah, why not.

**Comment by alexeevdv** [comment]
I have moved egg loading to ResourceManager::texture() method. Now we can implement loading from different places
