### ISSUE TITLE
Fix compilation warnings

### ISSUE THREAD

**Issue by phobos2077** [falltergeist/falltergeist#260]
- signed/unsigned mismatch
- unused members
- occurs in different classes

**Comment by dreamer-dead** [comment]
It seems that most of Clang warnings were fixed by #361 
I found this issue right after my code was merged.
I'll check for MSVS warnings.

**Comment by alexeevdv** [comment]
There are still a lot of GCC warnings. Most of them is about signed/unsigned

**Comment by phobos2077** [comment]
I believe it is important to keep our code free of warnings at all times. Otherwise it's harder to guarantee that it's working.
