### ISSUE TITLE
Add VMStackStringValue type

### ISSUE THREAD

**Issue by phobos2077** [falltergeist/falltergeist#293]
Need fourth data type to VM - strings. Currently strings are made as a subtype for VMStackPointerValue class.

* Strings are commonly used, dedicated type will make code clearer.
* Operations with strings differ from pointers (for instance - comparing with 0).

**Comment by alexeevdv** [comment]
:+1:

**Comment by janisozaur** [comment]
Few things that might be worth pointing out:
* right now strings appear to be one massive memleak. Whenever you push string onto stack, it's (almost?) never deleted when popped. E.g. https://github.com/falltergeist/falltergeist/blob/c885c835cc543d0900cf5901379314983b544693/src/VM/Handlers/Opcode8039Handler.cpp#L98
* Strings have arithmetic operations defined on them, don't forget to add these as well. E.g. same as above
