### ISSUE TITLE
Implement VM handlers for hexagon arithmetic functions

### ISSUE THREAD

**Issue by phobos2077** [falltergeist/falltergeist#316]
Implement handlers for *tile_in_tile_rect*, *tile_distance*, *tile_distance_objs*, *tile_num_in_direction*, *rotation_to_tile*.
Because of the stub implementation, **newr2** hangs in infinite loop on map enter.

As a bonus, *tile_is_visible* [80F8] can also be implemented.

**Comment by isage** [comment]
80D2 - tile_distance is already implemented
80D3 - tile_distance_obj is already implemented
80D5 - tile_num_in_direction is already implemented
814C - rotation_to_tile already is implemented
I've updated opcode database.
