### ISSUE TITLE
Mouse Pointer Lag

### ISSUE THREAD

**Issue by teep0** [falltergeist/falltergeist#347]
When the pointer is the right click yellow arrow pointer the game lags tremendously almost to unplayable state when moving the pointer around, This doesn't occur so much when the pointer is the red circle.

It happens on Linux, I'm unsure of whether it's happening on other platforms.

When the inventory is open this pointer is used and it doesn't lag for some reason, just when you switch to the pointer via right click ingame.

**Comment by alexeevdv** [comment]
This can be someway connected with pathfinding. We will look into this

**Comment by phobos2077** [comment]
This is related to "mousemove" event handling. Addressed in #416.
