### ISSUE TITLE
Lua integration architecture (discussion)

### ISSUE THREAD

**Issue by phobos2077** [falltergeist/falltergeist#383]
I'm not sure if @alexeevdv already made up his mind on how we are going to do this, but I wanted to share my thoughts on the subject.

The way I'd like to see it:
1. Game is initialized in C++ with all basic objects, like an empty state stack, event dispatcher, input, renderer, etc. **No states are defined or created in C++**
2. Then, game executes a single entry point to Lua scripts (something like `"_g.lua"`), a single lua state, global environment for all our logic. That's it, no logic at the engine side!
3. Script has access to constructors for all relevant classes: states, game object, UI controls, events. So it defines all states as a Lua "classes" derived from C++ LuaState class and adds them to the stack via `game.pushState()`.
**Edit:** do we really need LuaState class? We could probably implement State stack entirely on Lua by exposing `render()` method for UIs and game objects... The only question is how to handle events for UI controls...
4. To customize stuff we inherit Lua classes from C++ classes (states, objects, UI's) and override methods like "think", "handle". So each object can define it's logic at each frame.

To implement inheritance we can do something along those lines:
1. As a starting point, take solution from official Lua book: http://www.lua.org/pil/16.2.html
2. The first Lua class will act as a wrapper for userdata (C++) object. Via metatable it will pass calls and property access to underlying object.
3. Second, third, etc. classes will use the object of the previous class in hierarchy as it's __index, so eventually userdata object will be accessed for stuff that wasn't overridden.
4. To pass the underlying object to C++ functions (like `game.pushState()`, or `state:addUI()`) we will use some getter function or property with common name (like `myState.obj`). For example:
`game.pushState(mainMenuState.obj)`
The same will work for other types of object:
`locationState.hexagonGrid.at(2512):attach(superMutantWithMinigun.obj)`
`inventoryState:addUI(game.ui.buttons.RedCircleButton:new(100, 200))`
5. To override C++ functions (like handle() ) with Lua functions, we can add methods like `setHandleFunction()` that will accept Lua function and Lua table as arguments. For example, handle() method in LusState class can look something like that:

```
if (_handleFunction != nullptr) 
{
    _script.pushArgument(_luaTable); // self argument
    _script.callFunction(_handleFunction);
    // get result, etc.
}
```

To organize our code in a clean way, let's use "official" solution: http://www.lua.org/manual/5.1/manual.html#5.3
- We will use strict folder structure.
- Modules will be split by different namespaces (like UI, game, AI, states, etc.) each namespace maps to exact folder (like scripts/states/mainmenu.lua). 
- Each module will consist of a set of functions or classes closely related to each other.
- Large classes (like states) should probably be in their separate modules.
- Service logic like AI, will be used as a separate modules in appropriate states. We will keep our modules and classes separated and organized in consistent manner, so they can be easily reused and game logic could be reshaped.

It might be interesting to check out Lua API of this game engine:  
https://love2d.org/wiki/love

**Comment by phobos2077** [comment]
Some team members expressed concern that giving too much responsibility to scripts instead of the engine, will negatively affect productivity towards finishing the remake as soon as possible. Also, too little logic in C++ will result in some kind of "general-purpose" game engine, which are already plenty out there. 

I think it's very important to find some compromise as soon as possible. Right now it's difficult to start working on new features, without knowing what should be scripted and what is not, and how?
I see 2 ways.

1) Easiest "solution" is to drop scripting support altogether, or limit it dramatically (for example, to config files only) and continue with all states and game logic hard-coded. Though it won't require any redesign, in my opinion, it might even reduce our productivity in the long run, because C++ code is much harder to write and iterate. There are much less people who can handle C++ than those who can write in Lua, even without knowing the language, given some examples.
Second concern is that it will not allow good modding capabilities. More efforts will be required to rewrite large parts of the code after 1.0 for broader scripting support (possible modders might loose interest, if the engine won't include some modding options at the initial release).

2) We can keep base State class in C++ code, along with whole event system, but give scripts ability to define new states by creating some UI objects, attaching them to State and hooking Lua event handlers to them. 
Some states like Location or Worldmap may be implemented in C++, or maybe just the "meat" of them, giving ability to customize UI (buttons, indicators, etc.) in Lua. We can probably use existing C++ states for menus and such and replace them with Lua states as they are being rewritten.

Some candidates to consider scripting:
* AI, combat damage, radius, special effects calculations. Those are most interesting gameplay aspects which might require a lot of iteration (and scripts are good at this), and also - this is a primary interest for future modding. 
* Animation queues (movement and such) of critters in and out of combat. This includes attack sequences for different weapons (like rockets flying, explosion effects, etc.). 
If we define the whole Combat state in Lua, attaching handlers for clicks on critters and such, it will be natural to construct animation sequences also in scripts. This will allow to easily customize weapons behavior, add new weapon types to the game (smoke grenades? guided missiles? proper mines? you name it!). On our part it won't require any more work than C++ implementation (less work actually).
* Initialization of objects during map load: after map is loaded, script will be creating game objects from map information. This will give additional customization possibilities. Probably not very hard to change after engine is feature-complete.

3) ... I'm not sure what are other options? Opinions are welcome.

**Comment by JanSimek** [comment]
I would absolutely love to see lua scriptable Fallout 2 engine, but whatever you do, concentrate on making a playable prototype first. Tons of open-source projects died, because developers wanted to add huge features before the "basic" stuff.

**Comment by phobos2077** [comment]
They way I see it, it is faster to implement stuff in Lua than C++, after initial preparations. I think we can use existing States along with new Lua states, so we will keep pushing forward with new features and get back to refactoring at a later stage.

**Comment by alexeevdv** [comment]
@phobos2077 Second option is something that i was thinking of. But i'm still not sure about how to implement it

**Comment by alexeevdv** [comment]
@JanSimek "Playable prototype" is out main goal :)

**Comment by phobos2077** [comment]
I have made some improvements to Lua integration in my branch (see reference above). I will make a pull request later, since now it is based on another large branch that is not merged into master.
