### ISSUE TITLE
Can you add a list of implemented features

### ISSUE THREAD

**Issue by hhirsch** [falltergeist/falltergeist#407]
Hello,

I compiled the game and it worked sort of but seemed not feature complete. 
Can you please add a list of what is implemented?

**Comment by phobos2077** [comment]
[This graph](https://www.draw.io/#G0B76vtfiq4KzpUF8xdGpMRHlYMGc) shows a very rough estimate on what states are there (blue color indicates that we have a C++ class in place for this state, it doesn't mean it's done though).
Basically we are a long way from some kind of playable prototype. No combat system, no worldmap. Inventory system in early state. Basic dialogs works, but no barter, combat control, party system.
VM (interpreter for original game scripts) is done about 50% (all basic scripting works, but many opcodes require game logic to be implemented for them to make sense).

**Comment by hhirsch** [comment]
Hmm. Service blocked it says. Can not see the graph.

**Comment by phobos2077** [comment]
[Try this](https://drive.google.com/file/d/0B76vtfiq4KzpUF8xdGpMRHlYMGc/view?usp=sharing) link.

**Comment by hhirsch** [comment]
There is a tiny graphic at the location which will download as an xml file. I think a file with a list of what is implemented checked into the repository would do a better job.
