### ISSUE TITLE
Refactor UI::AnimatedImage and UI::Animation

### ISSUE THREAD

**Issue by phobos2077** [falltergeist/falltergeist#408]
Issues with this class:

* Has A LOT of code repetition. Difficult to read and maintain.
* Leaks memory. As far as I can tell, objects pointed by _slimeTextures, etc. are created but never deleted.

Suggestions: 
* Move all repeated code blocks into functions.
* Use `map<MASK, vector<unique_ptr<Texture>>>` for storing additional textures.

**Comment by isage** [comment]
Fixed.
