### ISSUE TITLE
Object outlines

### ISSUE THREAD

**Issue by phobos2077** [falltergeist/falltergeist#437]
![Screenshot](http://content.screencast.com/users/Kolosovsky/folders/Jing/media/469d83fb-435f-4eee-86a5-cd4782abf655/2015-10-15_1942.png)

Need to implement rendering of object outlines. As far as I know, they are not stored in FRM files and should be calculated dynamically.
Note that some outlines are color-animated (combat).

Usages:
* Hovering over ground items.
* Highlighting critters in different colors during combat turn.

**Comment by isage** [comment]
Implemented.
