### ISSUE TITLE
Rework use of non standard array declaration.

### ISSUE THREAD

**Issue by 8BitPimp** [falltergeist/falltergeist#449]
Faltergeist currently makes use of non standard array declarations (non const length).
MSVC does not support this extension, so I propose to rework the places its used.

The easiest aproach would be to allocate the space on the heap and then free it when it goes out of scope (unique_ptr).  The problem there however is that this construct seems to be used in a few inner loops and potential hot spots, which would rule out this change.

Does anyone have some advice for a good aproach?
I we were to use something like a frame memory allocator, we could avoid taking any speed hit.

I am happy to do any rework thats required, but It would be good to get input from you folks on this.

Mixer.cpp : 173
```
auto samples = acm->samples();
uint8_t memory[samples * 2];
```

Thanks

**Comment by Oppen** [comment]
Using https://msdn.microsoft.com/en-us/library/wb1s57t5.aspx should be exactly equivalent to dynamic arrays on the stack.
Otherwise, an acceptable approach is usually to study the code and find an upper bound, and allocate that upper bound and only alter the count of how many elements are valid.

**Comment by Oppen** [comment]
Alternatively, if it's a specific kind of object that is used very often, and object pool[0] might be a sane option for those AND their use in general.

[0]: https://en.wikipedia.org/wiki/Object_pool_pattern

**Comment by 8BitPimp** [comment]
After a quick look at _malloca (msvc) and alloca (posix), it seems they have a compatable interface allowing me to use typedef/using, instead of a macro which is a little bit more robust.  Luckily these constructs are only used for primitive types, so there are no constructors/destructors to worry about.
Thanks for the pointers Oppen, this seems like a viable solution, and I will try it out this evening if I get a chance.
If anyone has more feedback or suggestions, it would still be usefull.

**Comment by Oppen** [comment]
I thought of typedef'ing, but something sounds off about that. It's not a type, it's an operator, so while it would probably work, it sounds counter-intuitive. using might be better, although I didn't know that use of using (no pun intended).
You're welcome :)

**Comment by isage** [comment]
Use of alloca is discouraged, afaik, as it's compiler/implementation dependent. Sadly, VLAs didn't make it into C++14. 
For now, i've replacing this spots with dynamic allocation.

**Comment by isage** [comment]
Fixed.
