### ISSUE TITLE
error: GLSL 3.30 is not supported.

### ISSUE THREAD

**Issue by zero17333** [falltergeist/falltergeist#451]
I don't why this is happening. Maybe it has something to do with my Intel card. Maybe it's a bug?

**Comment by isage** [comment]
Yes, it has something to do with your intel card.
Engine requires GPU with OpenGL 3.3 or later.
We'll adapt it to older GPUs later.

**Comment by alexeevdv** [comment]
Looks like i have the same error on my notebook.
> GL Error 1280 at 184, init

My video: 
Mobile 4 Series Chipset Integrated Graphics Controller
Intel Corporation i945

**Comment by isage** [comment]
Yep: Version: 2.1 Mesa 10.1.3
And also it reports strange version: Using OpenGL 35347984.0
But don't worry, i have notebook with Intel 945GSE lying around, and i've started to port shaders to 2.1
I'll add support for older GPUs after finishing with lighting (which is almost done)

**Comment by alexeevdv** [comment]
That would be awesome :)

**Comment by trollworkout** [comment]
@zero17333  do you use windows 10? seems like windows 10 has limited support for integrated graphic drivers some of which only work with 1.5 opengl

**Comment by isage** [comment]
@trollworkout i'm pretty sure it won't even build on windows.

Intel supports opengl 3 only since Sandy Bridge (6th gen of Intel HD)
Intel GMA, however, is whole another story, being even older than IntelHD, going up to 1.5 on win and 2.1 on linux/osx. And then, there's also PoverVR based GPUs, used in Atom processors, which support 2.1.

Anyways, support for gl 2.1 based cards should be done by the end of week, i hope.
I'm afraid we can't/won't support anything lower 2.1, but i'll try.

**Comment by zero17333** [comment]
@trollworkout Actually I'm using Antergos Linux with a Haswell i3. It is odd how OpenGL is lower than I thought.

@isage Thank you for your effort

**Comment by isage** [comment]
@zero17333 can you provide log from console?

**Comment by zero17333** [comment]
I'll just give you the relevant stuff:

[INFO] [RENDERER] SDL_CreateWindow 640x480x32 - [OK]
[INFO] [RENDERER] Init OpenGL - [OK]
[INFO] [RENDERER] Using OpenGL 3.0
[INFO] [RENDERER] Renderer: Mesa DRI Intel(R) Haswell Mobile 
[INFO] [RENDERER] Version: 3.0 Mesa 11.1.2
[INFO] [RENDERER] Vendor: Intel Open Source Technology Center
[INFO] [RENDERER] Init GLEW - [OK]
[INFO] [RENDERER] Using GLEW 1.13.0


[INFO] Looking for Falltergeist data files
[INFO] Searching in directory: /home/bryan/Documents/falltergeist/data/movies.lst [FOUND]
[INFO] [RENDERER] Loading shader /home/bryan/Documents/falltergeist/data/shaders/default.fp
[INFO] [RENDERER] Loading shader /home/bryan/Documents/falltergeist/data/shaders/default.vp
[WARNING] [RENDERER] Failed to compile shader: '0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

[WARNING] [RENDERER] Failed to compile shader: '0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

[INFO] [RENDERER] Loading shader /home/bryan/Documents/falltergeist/data/shaders/sprite.fp
[INFO] [RENDERER] Loading shader /home/bryan/Documents/falltergeist/data/shaders/sprite.vp
[WARNING] [RENDERER] Failed to compile shader: '0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

[WARNING] [RENDERER] Failed to compile shader: '0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

[INFO] [RENDERER] Loading shader /home/bryan/Documents/falltergeist/data/shaders/font.fp
[INFO] [RENDERER] Loading shader /home/bryan/Documents/falltergeist/data/shaders/font.vp
[WARNING] [RENDERER] Failed to compile shader: '0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

[WARNING] [RENDERER] Failed to compile shader: '0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

[INFO] [RENDERER] Loading shader /home/bryan/Documents/falltergeist/data/shaders/animation.fp
[INFO] [RENDERER] Loading shader /home/bryan/Documents/falltergeist/data/shaders/animation.vp
[WARNING] [RENDERER] Failed to compile shader: '0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

[WARNING] [RENDERER] Failed to compile shader: '0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

[INFO] [RENDERER] Loading shader /home/bryan/Documents/falltergeist/data/shaders/tilemap.fp
[INFO] [RENDERER] Loading shader /home/bryan/Documents/falltergeist/data/shaders/tilemap.vp
[WARNING] [RENDERER] Failed to compile shader: '0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

[WARNING] [RENDERER] Failed to compile shader: '0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

[INFO] [RENDERER] [OK]
[INFO] [RENDERER] Generating buffers
GL Error 1281 at 184, init%

**Comment by teepean** [comment]
It might be fixed in Falltergeist itself. "It's very probably because you don't specifically ask the OpenGL implementation (in this case mesa) for Core Profile because only Haswell OpenGL core profile supports GLSL 3.30, as shown in this Haswell glxinfo dump: "

http://darmawan-salihun.blogspot.fi/2015/03/glsl-330-in-intel-haswell-cpu.html

**Comment by isage** [comment]
Yep, that's what i thought. Strange, tho, hasswell should support 3.3 on linux.
Anyway, should be fixed in latest master.

**Comment by teepean** [comment]
Thinking again SDL might be the place to fix the issue.

**Comment by isage** [comment]
@teepean we specifically ask for core profile. That's why we fall back to 2.1 (in latest master) on anything lower 3.2, because 3.1 is rare, and 3.0 shaders are deprecated in core profile.

**Comment by isage** [comment]
@zero17333 can you also post output of glxinfo | grep OpenGL

**Comment by isage** [comment]
Hm, that might be, however sdl/mesa bug. As we dont specify version, only that we want core context, mesa can still choose lowest, meh. I'll see what i can do, but first i need confirmation with info above

**Comment by zero17333** [comment]
Did someone change something between when I first posted this and now? It seems to working now for some reason after git pull and rebuilding. The first time I tried this it didn't work after doing it 7-8 times.

AFTER the rebuild it worked immediately and I can start the game

**Comment by isage** [comment]
Yes, as I've said, we added render path for opengl < 3.2, but i still need that glxinfo, because you should get ogl 3.3 on your system

**Comment by zero17333** [comment]
glxinfo | grep OpenGL                                     [21:06:44]
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.1.2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.1.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.1.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

**Comment by isage** [comment]
Yep, that's definitely mesa-related bug. I'll look into it.

**Comment by isage** [comment]
@zero17333 could you try adding after https://github.com/falltergeist/falltergeist/blob/master/src/Graphics/Renderer.cpp#L107

SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 0);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);

And see, it you'll get 3.3 profile instead of 3.0

**Comment by zero17333** [comment]
I added those lines between

SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);

and

SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);

and I got:

[CRITICAL] Init OpenGL - [FAIL]

It was definitely in Renderer.cpp.

**Comment by isage** [comment]
Yep, i've already tested this myself. Anyway, after https://github.com/falltergeist/falltergeist/pull/457 is merged you should finally get 3.2 context on mesa.
