### ISSUE TITLE
Can't find libglew

### ISSUE THREAD

**Issue by g4th** [falltergeist/falltergeist#456]
To get falltergeist to compile on linux mint 17.x I had to change line 30 of /cmake/modules/FindGLEW.cmake from:
NAMES GLEW glew
to:
NAMES GLEW gle

It kept telling me it couldn't find libglew, so I investigated and there was no libglew.so in /usr/lib/ only libgle.so.

I installed glew with apt so I'm not sure why the library is named wrong?

**Comment by isage** [comment]
Because libgle is "OpenGL tubing and extrusion library", while libglew is "OpenGL Extension Wrangler" and its two completely different things.

What you need is libglew-dev

**Comment by g4th** [comment]
Ok, I understand.

libGLEW.so does not exist in any of the directories findGLEW.cmake is searching for it on my machine. 

it exists in directory /usr/lib/x86_64-linux-gnu

**Comment by isage** [comment]
findGLEW.cmake searches in /usr/lib/, /usr/lib/x86_64-linux-gnu is **inside** /usr/lib so it's searched too.
And it is successful in doing so.

**Comment by g4th** [comment]
Hahaha, ok. You are right, it is working now for some odd reason it wasn't before and glew was installed.

Holy shit, I'm tired. Closing this, forgive my stupidity.
