### ISSUE TITLE
Can't open shaders (the files do exist)

### ISSUE THREAD

**Issue by shsorbom** [falltergeist/falltergeist#460]
[INFO] [RENDERER] Loading default shaders
[INFO] Looking for Falltergeist data files
[INFO] Searching in directory: /usr/bin/data/movies.lst [NOT FOUND]
[INFO] Searching in directory: /home/shawn/.local/share/falltergeistdata/movies.lst [NOT FOUND]
[INFO] Searching in directory: /usr/bin//../share/falltergeistdata/movies.lst [FOUND]
[INFO] [RENDERER] Loading shader /usr/bin//../share/falltergeistdata/shaders/32/default.fp
[INFO] [RENDERER] Loading shader /usr/bin//../share/falltergeistdata/shaders/32/default.vp
**[CRITICAL] Can't open shader source /usr/bin//../share/falltergeistdata/shaders/32/default.fp**

What should I do? As stated, the files do exist.

The complete output is below:

[INFO] Loading config from /home/shawn/.config/falltergeist/config.ini
[INFO] [INI] start parsing config file.
[DEBUG] [INI] start section: `audio`
[DEBUG] [INI] integer value found for property `buffer_size`: 512
[DEBUG] [INI] boolean value found for property `enabled`: true
[DEBUG] [INI] double value found for property `master_volume`: 1
[DEBUG] [INI] string value found for property `music_path`: data/sound/music/
[DEBUG] [INI] double value found for property `music_volume`: 1
[DEBUG] [INI] double value found for property `sfx_volume`: 1
[DEBUG] [INI] double value found for property `voice_volume`: 1
[DEBUG] [INI] start section: `game`
[DEBUG] [INI] boolean value found for property `display_fps`: true
[DEBUG] [INI] boolean value found for property `display_mouse_position`: true
[DEBUG] [INI] boolean value found for property `force_location`: false
[DEBUG] [INI] string value found for property `init_location`: klamall
[DEBUG] [INI] boolean value found for property `worldmap_fullscreen`: false
[DEBUG] [INI] start section: `logger`
[DEBUG] [INI] boolean value found for property `colors`: true
[DEBUG] [INI] string value found for property `level`: info
[DEBUG] [INI] start section: `preferences`
[DEBUG] [INI] double value found for property `brightness`: 1
[DEBUG] [INI] integer value found for property `combat_difficulty`: 1
[DEBUG] [INI] boolean value found for property `combat_looks`: false
[DEBUG] [INI] boolean value found for property `combat_messages`: true
[DEBUG] [INI] integer value found for property `combat_speed`: 0
[DEBUG] [INI] boolean value found for property `combat_taunts`: false
[DEBUG] [INI] integer value found for property `game_difficulty`: 1
[DEBUG] [INI] boolean value found for property `item_highlight`: false
[DEBUG] [INI] boolean value found for property `language_filter`: false
[DEBUG] [INI] double value found for property `mouse_sensitivity`: 1
[DEBUG] [INI] boolean value found for property `player_speedup`: false
[DEBUG] [INI] boolean value found for property `running`: false
[DEBUG] [INI] boolean value found for property `subtitles`: false
[DEBUG] [INI] boolean value found for property `target_highlight`: false
[DEBUG] [INI] double value found for property `text_delay`: 0
[DEBUG] [INI] integer value found for property `violence_level`: 2
[DEBUG] [INI] start section: `video`
[DEBUG] [INI] boolean value found for property `fullscreen`: false
[DEBUG] [INI] integer value found for property `height`: 480
[DEBUG] [INI] integer value found for property `scale`: 0
[DEBUG] [INI] integer value found for property `width`: 640
[INFO] Looking for Fallout data files
[INFO] Searching in directory: /usr/bin/ master.dat [NOT FOUND]
[INFO] Searching in directory: /home/shawn/.local/share/falltergeist master.dat [FOUND]
[INFO] Searching in directory: /home/shawn/.local/share/falltergeist critter.dat [FOUND]
[INFO] [VIDEO] Renderer initialization - [OK]
[INFO] [GAME] Falltergeist 0.3.0 (Linux)
[INFO] [GAME] Opensource Fallout 2 game engine
[INFO] [RENDERER] SDL_CreateWindow 640x480x32 - [OK]
[INFO] [RENDERER] Init OpenGL - [OK]
[INFO] [RENDERER] Using OpenGL 3.3
[INFO] [RENDERER] Renderer: Mesa DRI Intel(R) Haswell Mobile 
[INFO] [RENDERER] Version string: 3.3 (Core Profile) Mesa 10.3.2
[INFO] [RENDERER] Vendor: Intel Open Source Technology Center
[INFO] [RENDERER] Render path: OpenGL 3.0+
[INFO] [RENDERER] Init GLEW - [OK]
[INFO] [RENDERER] Using GLEW 1.10.0
[INFO] [RENDERER] Extensions: 
[INFO] [RENDERER] GL_ARB_ES2_compatibility
[INFO] [RENDERER] GL_ARB_ES3_compatibility
[INFO] [RENDERER] GL_ARB_base_instance
[INFO] [RENDERER] GL_ARB_blend_func_extended
[INFO] [RENDERER] GL_ARB_buffer_storage
[INFO] [RENDERER] GL_ARB_clear_buffer_object
[INFO] [RENDERER] GL_ARB_clear_texture
[INFO] [RENDERER] GL_ARB_compressed_texture_pixel_storage
[INFO] [RENDERER] GL_ARB_conditional_render_inverted
[INFO] [RENDERER] GL_ARB_copy_buffer
[INFO] [RENDERER] GL_ARB_copy_image
[INFO] [RENDERER] GL_ARB_conservative_depth
[INFO] [RENDERER] GL_ARB_debug_output
[INFO] [RENDERER] GL_ARB_depth_buffer_float
[INFO] [RENDERER] GL_ARB_depth_clamp
[INFO] [RENDERER] GL_ARB_derivative_control
[INFO] [RENDERER] GL_ARB_draw_buffers
[INFO] [RENDERER] GL_ARB_draw_buffers_blend
[INFO] [RENDERER] GL_ARB_draw_elements_base_vertex
[INFO] [RENDERER] GL_ARB_draw_instanced
[INFO] [RENDERER] GL_ARB_explicit_attrib_location
[INFO] [RENDERER] GL_ARB_explicit_uniform_location
[INFO] [RENDERER] GL_ARB_fragment_coord_conventions
[INFO] [RENDERER] GL_ARB_fragment_shader
[INFO] [RENDERER] GL_ARB_framebuffer_object
[INFO] [RENDERER] GL_ARB_framebuffer_sRGB
[INFO] [RENDERER] GL_ARB_get_program_binary
[INFO] [RENDERER] GL_ARB_gpu_shader5
[INFO] [RENDERER] GL_ARB_half_float_pixel
[INFO] [RENDERER] GL_ARB_half_float_vertex
[INFO] [RENDERER] GL_ARB_instanced_arrays
[INFO] [RENDERER] GL_ARB_internalformat_query
[INFO] [RENDERER] GL_ARB_invalidate_subdata
[INFO] [RENDERER] GL_ARB_map_buffer_alignment
[INFO] [RENDERER] GL_ARB_map_buffer_range
[INFO] [RENDERER] GL_ARB_multi_bind
[INFO] [RENDERER] GL_ARB_occlusion_query2
[INFO] [RENDERER] GL_ARB_pixel_buffer_object
[INFO] [RENDERER] GL_ARB_point_sprite
[INFO] [RENDERER] GL_ARB_provoking_vertex
[INFO] [RENDERER] GL_ARB_robustness
[INFO] [RENDERER] GL_ARB_sample_shading
[INFO] [RENDERER] GL_ARB_sampler_objects
[INFO] [RENDERER] GL_ARB_seamless_cube_map
[INFO] [RENDERER] GL_ARB_seamless_cubemap_per_texture
[INFO] [RENDERER] GL_ARB_separate_shader_objects
[INFO] [RENDERER] GL_ARB_shader_atomic_counters
[INFO] [RENDERER] GL_ARB_shader_bit_encoding
[INFO] [RENDERER] GL_ARB_shader_objects
[INFO] [RENDERER] GL_ARB_shader_texture_lod
[INFO] [RENDERER] GL_ARB_shading_language_packing
[INFO] [RENDERER] GL_ARB_shading_language_420pack
[INFO] [RENDERER] GL_ARB_sync
[INFO] [RENDERER] GL_ARB_texture_buffer_object
[INFO] [RENDERER] GL_ARB_texture_buffer_object_rgb32
[INFO] [RENDERER] GL_ARB_texture_buffer_range
[INFO] [RENDERER] GL_ARB_texture_compression_bptc
[INFO] [RENDERER] GL_ARB_texture_compression_rgtc
[INFO] [RENDERER] GL_ARB_texture_cube_map_array
[INFO] [RENDERER] GL_ARB_texture_float
[INFO] [RENDERER] GL_ARB_texture_gather
[INFO] [RENDERER] GL_ARB_texture_mirror_clamp_to_edge
[INFO] [RENDERER] GL_ARB_texture_multisample
[INFO] [RENDERER] GL_ARB_texture_non_power_of_two
[INFO] [RENDERER] GL_ARB_texture_query_levels
[INFO] [RENDERER] GL_ARB_texture_query_lod
[INFO] [RENDERER] GL_ARB_texture_rectangle
[INFO] [RENDERER] GL_ARB_texture_rgb10_a2ui
[INFO] [RENDERER] GL_ARB_texture_rg
[INFO] [RENDERER] GL_ARB_texture_storage
[INFO] [RENDERER] GL_ARB_texture_storage_multisample
[INFO] [RENDERER] GL_ARB_texture_view
[INFO] [RENDERER] GL_ARB_texture_swizzle
[INFO] [RENDERER] GL_ARB_timer_query
[INFO] [RENDERER] GL_ARB_uniform_buffer_object
[INFO] [RENDERER] GL_ARB_vertex_array_bgra
[INFO] [RENDERER] GL_ARB_vertex_array_object
[INFO] [RENDERER] GL_ARB_vertex_attrib_binding
[INFO] [RENDERER] GL_ARB_vertex_shader
[INFO] [RENDERER] GL_ARB_vertex_type_10f_11f_11f_rev
[INFO] [RENDERER] GL_ARB_vertex_type_2_10_10_10_rev
[INFO] [RENDERER] GL_ARB_viewport_array
[INFO] [RENDERER] GL_EXT_abgr
[INFO] [RENDERER] GL_EXT_blend_equation_separate
[INFO] [RENDERER] GL_EXT_draw_buffers2
[INFO] [RENDERER] GL_EXT_draw_instanced
[INFO] [RENDERER] GL_EXT_framebuffer_blit
[INFO] [RENDERER] GL_EXT_framebuffer_multisample
[INFO] [RENDERER] GL_EXT_framebuffer_multisample_blit_scaled
[INFO] [RENDERER] GL_EXT_framebuffer_sRGB
[INFO] [RENDERER] GL_EXT_packed_depth_stencil
[INFO] [RENDERER] GL_EXT_packed_float
[INFO] [RENDERER] GL_EXT_pixel_buffer_object
[INFO] [RENDERER] GL_EXT_provoking_vertex
[INFO] [RENDERER] GL_EXT_shader_integer_mix
[INFO] [RENDERER] GL_EXT_texture_array
[INFO] [RENDERER] GL_EXT_texture_compression_dxt1
[INFO] [RENDERER] GL_ANGLE_texture_compression_dxt3
[INFO] [RENDERER] GL_ANGLE_texture_compression_dxt5
[INFO] [RENDERER] GL_EXT_texture_compression_rgtc
[INFO] [RENDERER] GL_EXT_texture_compression_s3tc
[INFO] [RENDERER] GL_EXT_texture_filter_anisotropic
[INFO] [RENDERER] GL_EXT_texture_integer
[INFO] [RENDERER] GL_EXT_texture_shared_exponent
[INFO] [RENDERER] GL_EXT_texture_snorm
[INFO] [RENDERER] GL_EXT_texture_sRGB
[INFO] [RENDERER] GL_EXT_texture_sRGB_decode
[INFO] [RENDERER] GL_EXT_texture_swizzle
[INFO] [RENDERER] GL_EXT_timer_query
[INFO] [RENDERER] GL_EXT_transform_feedback
[INFO] [RENDERER] GL_EXT_vertex_array_bgra
[INFO] [RENDERER] GL_OES_EGL_image
[INFO] [RENDERER] GL_OES_read_format
[INFO] [RENDERER] GL_KHR_debug
[INFO] [RENDERER] GL_3DFX_texture_compression_FXT1
[INFO] [RENDERER] GL_AMD_conservative_depth
[INFO] [RENDERER] GL_AMD_draw_buffers_blend
[INFO] [RENDERER] GL_AMD_seamless_cubemap_per_texture
[INFO] [RENDERER] GL_AMD_shader_trinary_minmax
[INFO] [RENDERER] GL_AMD_vertex_shader_layer
[INFO] [RENDERER] GL_AMD_vertex_shader_viewport_index
[INFO] [RENDERER] GL_APPLE_object_purgeable
[INFO] [RENDERER] GL_ATI_blend_equation_separate
[INFO] [RENDERER] GL_ATI_texture_float
[INFO] [RENDERER] GL_IBM_multimode_draw_arrays
[INFO] [RENDERER] GL_MESA_pack_invert
[INFO] [RENDERER] GL_MESA_texture_signed_rgba
[INFO] [RENDERER] GL_NV_conditional_render
[INFO] [RENDERER] GL_NV_depth_clamp
[INFO] [RENDERER] GL_NV_packed_depth_stencil
[INFO] [RENDERER] GL_S3_s3tc
[INFO] [RENDERER] Loading default shaders
[INFO] Looking for Falltergeist data files
[INFO] Searching in directory: /usr/bin/data/movies.lst [NOT FOUND]
[INFO] Searching in directory: /home/shawn/.local/share/falltergeistdata/movies.lst [NOT FOUND]
[INFO] Searching in directory: /usr/bin//../share/falltergeistdata/movies.lst [FOUND]
[INFO] [RENDERER] Loading shader /usr/bin//../share/falltergeistdata/shaders/32/default.fp
[INFO] [RENDERER] Loading shader /usr/bin//../share/falltergeistdata/shaders/32/default.vp
[CRITICAL] Can't open shader source /usr/bin//../share/falltergeistdata/shaders/32/default.fp

**Comment by isage** [comment]
Are you by any chance used "make install"?

**Comment by shsorbom** [comment]
yes. I originally tried building it as a debian package, but running "make install" manually, (then re-testing) produced the same result. Could it be my video card?

**Comment by isage** [comment]
No, your card is fine. It's something with installation. I'll look into that. Meanwhile, i recommend removing installed files and just run binary from source dir.

**Comment by shsorbom** [comment]
Voila!  It worked. If you want me to try anything else, don't hesitate to ask.

**Comment by shsorbom** [comment]
Further testing seems to suggest that it will work if the falltergeist binary and the data directory are both in the same place on the filesystem. Nowhere else yet.
