### ISSUE TITLE
CrossPlatform::getExecutableDirectory() returns NULL on OpenBSD

### ISSUE THREAD

**Issue by mulander** [falltergeist/falltergeist#465]
Hi,

I'm attempting an OpenBSD port for Falltergeist and the first stumbling block is the path finding.

[INFO] Looking for Fallout data files
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Abort trap (core dumped)

This fails on the mentioned calls to getExecutableDirectory

```C++
std::string CrossPlatform::getExecutableDirectory()
{
    char* buffer=SDL_GetBasePath();
    std::string path(buffer);
    SDL_free(buffer);
    return path;
}
```

SL_GetBasePath() returns NULL and there is no system specific way to get the executables current directory on OpenBSD (we don't have a procfs).

Commenting out calls to this specific functions allows the loading to progress (up to showing a loading screen).

**Comment by isage** [comment]
So use SDL_strdup("./") for *bsd.
