### ISSUE TITLE
Character screen warped at 1920x1080 resolution

### ISSUE THREAD

**Issue by shsorbom** [falltergeist/falltergeist#480]
![falltergiest-wide-bug](https://cloud.githubusercontent.com/assets/8840213/15808985/a6e780a8-2b3a-11e6-8b22-c76ccfd37e07.png)

**Comment by isage** [comment]
That was fixed ages ago in https://github.com/falltergeist/falltergeist/commit/a53105d6caa18e61d3087ea34dfe2f94a66c3bf3

**Comment by shsorbom** [comment]
Sorry I will merge with upstream again tomorrow. I didn't realize I had fallen behind.
