### ISSUE TITLE
Fallout 2 English VM Info

### ISSUE THREAD

**Issue by bludwulf** [falltergeist/falltergeist#489]
I don't know where else to ask since irc seems empty always, but I was wondering if the information at http://teamx.ru/site_arc/docs/fop_lite_htm_050327.rar is available anywhere in English because Google translate does a horrible job translating it to English and I can't understand the descriptions of the opcodes.

I can't find the information anywhere else.

Here's a table I made to better visualize opcodes that Fallout 2 scripts use (according to the aforementioned document) which as of now do not yet have handlers implemented in Falltergeist from what I can tell.

![table image](http://i.imgur.com/CjvGgb9.jpg)

**Comment by isage** [comment]
Most of opcodes are described in official BIS Mapper documentation.

**Comment by bludwulf** [comment]
Where can I find this?

**Comment by isage** [comment]
http://www.nma-fallout.com/resources/bis-mapper.55/ or any other place. 
docs are in scripts/DOCS

**Comment by bludwulf** [comment]
That one is easier on the eyes, thanks. Going to close this now

**Comment by JanSimek** [comment]
Maybe you could add that opcode table to the wiki where others can add/update the description and status in Falltergeist : https://github.com/falltergeist/falltergeist/wiki

**Comment by isage** [comment]
M. We do have page with opcodes status on website, but sadly, it's closed with authorization (don't ask, Dmitri did it)

**Comment by alexeevdv** [comment]
Well... i will make this section open for anyone in the couple of days
