### ISSUE TITLE
MvePlayer opcodes crash

### ISSUE THREAD

**Issue by Zervox** [falltergeist/falltergeist#507]
having a crash related to
```
const auto& opcodes = *_chunk->opcodes();
    for (const auto& opcode : opcodes)
```
in void MvePlayer::_processChunk()

changing it to
```
const auto opcodes = *_chunk->opcodes();
    for (const auto opcode : opcodes)
```
fixes the crash.

**Comment by phobos2077** [comment]
Wasn't that already fixed here: https://github.com/falltergeist/falltergeist/pull/504/commits/3d502fe98e08bc81fd03e4f0f1713807f184a62b ?

**Comment by Zervox** [comment]
I am using VS2017-Win10 same as you I believe.
