### ISSUE TITLE
Format weird functions does uneeded processing

### ISSUE THREAD

**Issue by Zervox** [falltergeist/falltergeist#516]
all these files already calls _initialize on creation, main problem I find with this is that the function is also that it is a virtualized functione even with the if(_initialized) check in _initialized of each type.

in Gam File.cpp
GVars() and MVars()
calls _initialize(), wasteful call

in Lst File.cpp
strings()
calls _initialize(), wasteful call

in Sve File.cpp
getSubLine(int frame)
calls _initialize(), same issue as above

in Lip File.cpp
acmName()
phonemesCount()
markersCount()
acmSize()
timestamps()
phonemes()
calls _initialize() same issues as above

**Comment by phobos2077** [comment]
Duplicates #512.
