### ISSUE TITLE
player panel mouse scrolling handler

### ISSUE THREAD

**Issue by Zervox** [falltergeist/falltergeist#525]
https://github.com/Zervox/falltergeist/blob/bb519dc82a943aa35b74f3f7f5d46db4870e4c54/src/UI/PlayerPanel.cpp#L74-L90
this code I am not sure should belong to PlayerPanel but instead handled inside the mouse event handling(that is if it actually does anything)

Edit:
seems like it allows you to change states between looking/selecting and moving when on the map, after having used the PlayerPanel definitively should be moved out the class or handled better.

**Comment by phobos2077** [comment]
Duplicates: #422

PS: Try giving better names/descriptions for your issues and PRs.
