### ISSUE TITLE
segafult when move between locations

### ISSUE THREAD

**Issue by vvbalashoff** [falltergeist/falltergeist#547]
I have it on two separate PC. On my work PC I see new location and then I have segfault, on my home PC I have segfault just when I walk into green zone. I have following:
===
[INFO] [MESSAGE] You are once more in the village of your birth, Arroyo.
[INFO] [MESSAGE] You passed the trials of Arroyo.
[INFO] [MESSAGE] You gain 600 experience points.
[CRITICAL] [LOCATION]  PID: 0x5000016
 name: Exit Grid
 exitMapNumber: 5
 exitElevationNumber: 0
 exitHexagonNumber: 16886
 exitDirection: 0

[INFO] [GAME] Tilemap tiles 1232
[INFO] [GAME] Tilemap uniq tiles 184
[INFO] [GAME] Tilemap atlases 1
[INFO] [GAME] Tilemap generated in 69
[INFO] [GAME] Tilemap tiles 53
[INFO] [GAME] Tilemap uniq tiles 40
[INFO] [GAME] Tilemap atlases 1
[INFO] [GAME] Tilemap generated in 14
[INFO] [MESSAGE] You are are standing at the Great Bridge, passageway from your village to the vast Wasteland.
Segmentation fault

===

**Comment by JanSimek** [comment]
If you step on an exit hexagon that is on the edge of the "exit area" then it doesn't crash. If you step on the second in the line or any one further on it crashes.

**Comment by alexeevdv** [comment]
Thanks for info. I'll fix it today. I think i know what is causing this problem
