### ISSUE TITLE
Скомпилируйте исходники проекта.

### ISSUE THREAD

**Issue by FakelsHub** [falltergeist/falltergeist#550]
И выложите их для скачивания, чтобы можно было попробовать и протестировать.

**Comment by alexeevdv** [comment]
В ближайших планах автоматические сборки пакетов под Linux  и Windows. Каждый релиз можно будет скачать в скомпилированном виде. Думаю в течение недели эта задача будет решена

**Comment by FakelsHub** [comment]
Может ну его нафиг эту автоматизацию, выложите просто собранный екзешник, а то эта автоматизация затянется на года.

**Comment by FakelsHub** [comment]
Что там компиляция накрылась медным тазом?)

**Comment by s1nka** [comment]
А под какую ОСь собрать то нужно?
з.ы. ИМХО тему лучше прикрыть и ждать все же автоматической сборки пакетов.

**Comment by FakelsHub** [comment]
Не будет никакой автоматической сборки)
Проект по сути рипнулся.

**Comment by alexeevdv** [comment]
По сути да. Времени у меня на проект нет. И не предвидится в ближайшее время. Может на пенсию выйду, стану посвободнее и допилю :)

**Comment by alexeevdv** [comment]
Я конечно буду время от времени засылать какие-то правки, доработки, но это больше в порядке исключения, а не планомерной полноценной работы над проектом

**Comment by phobos2077** [comment]
Очень жаль.. у меня примерная такая же история. :cry:

**Comment by burner1024** [comment]
А вообще последнюю версию кто-нибудь проверял под windows? У меня и develop, и 0.3.1 падают при запуске, что нативно, что под wine.

**Comment by alexeevdv** [comment]
Duplicate #576
