### ISSUE TITLE
Steam version doesn't provide movies.lst

### ISSUE THREAD

**Issue by rapenne-s** [falltergeist/falltergeist#556]
[What happens and when]
I copied the files installed from Steam (windows) of Fallout 2

I have those files in the path needed:

``
$ find /home/solene/.local/share/falltergeist/ -type f
/home/solene/.local/share/falltergeist/critter.dat
/home/solene/.local/share/falltergeist/data/art/tiles/grid000.FRM
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/ARCAVES.SAV
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/ARTEMPLE.SAV
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/AUTOMAP.SAV
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000062.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000079.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000089.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000097.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000107.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000136.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000152.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000160.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000161.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000162.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000163.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000164.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000165.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000191.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000195.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000196.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000197.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000265.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000342.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000379.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000380.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000381.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000384.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/critters/00000471.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/proto/items/00000455.pro
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/SAVE.DAT
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/sfallfs.sav
/home/solene/.local/share/falltergeist/data/SAVEGAME/SLOT01/sfallgv.sav
/home/solene/.local/share/falltergeist/data/worldmap.dat
/home/solene/.local/share/falltergeist/master.dat
``

### Steps to Reproduce
./falltergeist
[....]
[INFO] [RENDERER] Loading default shaders
[INFO] Looking for Falltergeist data files
[WARNING] SDL_GetBasePath() not able to obtain a path on this platform
[WARNING] SDL_GetBasePath() not able to obtain a path on this platform
[INFO] Searching in directory: .//data/movies.lst [NOT FOUND]
[INFO] Searching in directory: /home/solene/.local/share/falltergeist/data/movies.lst [NOT FOUND]
[CRITICAL] Falltergeist data files are not found!

### System

falltergeist commit 6a24ee8058005636e90b088f20bad4940792543e (jan 2018)
OpenBSD-current (future 6.4)

### Notes

Where to buy the games to use falltergeist ? This information should be available somewhere, I would submit a patch for this but I don't know which shop provide a compatible fallout 2 files.

Fun fact, Fallout 2 installed on steam in french has all files name uppercase while installed in english the files are lowercase...

**Comment by JanSimek** [comment]
I am using the version from GOG.com

**Comment by rapenne-s** [comment]
I have been able to download setup_fallout2_2.1.0.17.exe from GOG, using innoextract on it, it doesn't provide movies.lst file.

**Comment by s1nka** [comment]
[movies.lst](https://github.com/falltergeist/falltergeist/blob/develop/data/movies.lst)
Just get data dir from [this](https://github.com/falltergeist/falltergeist/tree/develop/data) and put in ~/.local/share/falltergeist/

**Comment by rapenne-s** [comment]
I've been able to start the game with this directory. Is it needed for all installation? (CD, Gog etc..)

**Comment by s1nka** [comment]
Yes

**Comment by phobos2077** [comment]
movies.lst is not a part of the original game distribution, it was created for falltergeist only (this list was hard-coded into the engine before).

**Comment by alexeevdv** [comment]
Falltergest has some additional files in order to be able to work. It is not an issue.... therefore closed
