### ISSUE TITLE
Game won't launch with radeon mesa driver

### ISSUE THREAD

**Issue by AdamFx990** [falltergeist/falltergeist#577]
After pulling the latest source and building, I was unable to launch the game with mesa 19.1.5 on a Radeon Vega 64.

`
[INFO] Looking for Fallout data files
[INFO] Searching in directory: /home/adam/Projects/falltergeist/ master.dat [FOUND]
[INFO] Searching in directory: /home/adam/Projects/falltergeist/ critter.dat [FOUND]
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/local/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/local/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/local/lib/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  116
  Current serial number in output stream:  115
`

### Expected Behavior

The engine should launch as normal.

### Steps to Reproduce
1. Pull the latest source from the _devlop_ branch
2. Build (cmake . && make)
3. run ./falltergeist on a system with mesa amdgpu drivers.

### System
- **Falltergeist:** c8416ca086f451bc98f9634a9d426956e7d2e3c5
- **Operating System:** Manjaro /w linux 5.2.11 x86_64
- **Fallout:** Fallout 2 GOG

**Output of glxinfo | grep *OpenGL*:
`
OpenGL vendor string: X.Org
OpenGL renderer string: Radeon RX Vega (VEGA10, DRM 3.32.0, 5.2.11-1-MANJARO, LLVM 8.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.1.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.1.5
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.1.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
`

**Comment by alexeevdv** [comment]
Thanks for the report. It might be helpful in the future

**Comment by AdamFx990** [comment]
I've tested with GCN and terrascale and it seems to run fine now. Possibly a mesa update fixed it.
