### ISSUE TITLE
Add new opcode set_proto_data (from sfall)

### ISSUE THREAD

**Issue by FakelsHub** [falltergeist/falltergeist#588]
`0x8205 - void set_proto_data(int pid, int offset, int value)`
https://fakelshub.github.io/sfall-documentation/objects-and-prototypes/#set_proto_data

Add a new opcode from sfall and test its operation as described.

It seems to me that the engine will not be able to work correctly with objects as the original fallout2 engine does.

**Comment by alexeevdv** [comment]
Currently there are no plans to support anything except vanilla Fallout. But i don't see why it can't be implemented in the future. Technically there are no limitations of any kind for it

**Comment by FakelsHub** [comment]
У меня какие-то сомнения по поводу того, можно ли будет корректно добавить функции от sfall. 
Изучая код движка того как он работает с объектами игры, получается так, что каждый объект после его создания, больше не зависит от его прототипа, т.е. после его создания объект получает данные из его прототипа, и дальше существует в памяти и не завит от изменений его основного прототипа. Может это не так, и я здесь ошибаюсь, т.к. не вижу всей архитектуры кода.
В то время fallout читает данные напрямую из прототипа который загружен в память.

**Comment by FakelsHub** [comment]
У меня какие-то сомнения по поводу того, можно ли будет корректно добавить функции от sfall. 
Изучая код движка того как он работает с объектами игры, получается так, что каждый объект после его создания, больше не зависит от его прототипа, т.е. после его создания объект получает данные из его прототипа, и дальше существует в памяти и не завит от изменений его основного прототипа. Может это не так, и я здесь ошибаюсь, т.к. не вижу всей архитектуры кода.
В то время fallout читает данные напрямую из прототипа который загружен в память.

**Comment by alexeevdv** [comment]
По работе с объектами есть много планов, но как и относительно всего остального очень мало времени. Я практически не знаком с sfall и не знаю нюансов работы и на что он завязан. Суть этого проекта и его приоритеты совсем другие. Имея открытый движок необходимость в хаках вроде sfall отпадает, т.к. можно делать любые извращения на уровне движка. Мы стараемся насколько это возможно держать в уме совместимость с существующими модами, но основная цель это полная поддержка оригинального фолача. Все остальное вторично и не приоритетно. У этого проекта и так не очень много шансов дойти до финиша (учитывая отсутствие у меня свободного времени), поэтому распылять силы еще и на специальную поддержку sfall я точно не буду. Если получится не сломать совместимость - хорошо. Не получится - пусть этим занимается тот у кого есть свободное время :)

**Comment by FakelsHub** [comment]
> Я практически не знаком с sfall и не знаю нюансов работы и на что он завязан. 

Суть sfall - это по сути продолжение доработки движка не имеющего исходников, т.е как обычно пишем новые фукции/возможности и заменяем/дополняем ими уже существующий код в движке. Получается такое не удобное программирование, когда не видно самого исходного кода движка :-)

**Comment by phobos2077** [comment]
Согласен с @alexeevdv . Я бы в рамках проекта не добавлял ничего из sfall. Весь смысл римейка движка в том чтобы отпадала необходимость в низкоуровневых хаках на которых работает sfall. Тут как мне кажется если подобный проект дойдет до 1.0 (Fallout 1 и 2 полностью проходимы в Vanilla), можно будет реализовать поддержку sfall скриптов в каком-нибудь виде как прослойку совместимости, некий плагин.

Проблема в том что многие игроки привыкли играть в Фол с модами которые требуют скриптовые фичи Sfall. И если многие опкоды ещё как-то можно эмулировать на новом движке, штуки типа хук скриптов или еще хуже, низкоуровневых вызовов (вроде set_proto_data или опкодов которые лезут в память напрямую) - вообще непонятно как поддерживать.

Мне кажется такие моды проще будет обновить, переписать скрипты под новый движок. Очень многие игроки (думаю большинство, особенно за пределами СНГ) не отказались бы понастольгировать в фол и в ваниле на каком-нибудь линуксе с полноценной поддержкой современных систем. Без вайнов и прочего. Как я понял это и была основная цель проекта изначально.

Самые популярные моды вроде Restoration Project используют фичи sfall по минимуму. Насколько помню там кроме кастомных перков и нескольких уродливых глобальных скриптов, ничего особого и нет.

Если говорить про обновленный скриптовый язык SSL который идет с Sfall, то он не требует поддержки виртуальной машины. Если VM будет корректно реализована по части базовых инструкций типа условий и переходов (а это уже вроде бы работает как надо), фичи типа foreach, short-circuit evaluation и тд заработают сами. Всякие list_begin и sfall arrays придется конечно эмулировать...

**Comment by FakelsHub** [comment]
> Я бы в рамках проекта не добавлял ничего из sfall.

До релизной версии и не стоит.
Но я бы порекомендовал хоть немного придерживаться оригинала.
Чтобы потом не было "попа боль" в тотальном переписывании готового кода под новый скриптовой фунционал от sfall.

> штуки типа хук скриптов или еще хуже, низкоуровневых вызовов (вроде set_proto_data или опкодов которые лезут в память напрямую) - вообще непонятно как поддерживать.

с set_proto_data - вроде все просто, проход по каждому объекту. (сейчас так в sfall сделано для прототипов NPC)
хуки вроде тоже не проблема, но уже сложнее (переписывать код точно придется).

**Comment by phobos2077** [comment]
> Но я бы порекомендовал хоть немного придерживаться оригинала.
> Чтобы потом не было "попа боль" в тотальном переписывании готового кода под новый скриптовой фунционал от sfall.

Игровой движок реализует определенный функионал, необходимый для игры. И должен иметь адекватную архитектуру. Поддержка sfall это не переписывание, а добавление прослойки совместимости. Большинство фич sfall всё равно идут от необходимости обойти отсутствие исходников движка и будут просто не нужны. Стоит рассматривать это как новый движок, а не повторение старого вплоть до внутренных особенностей. Главное - игровой процесс. А то что внутри можно написать по современному.

**Comment by FakelsHub** [comment]
> Поддержка sfall это не переписывание, а добавление прослойки совместимости. 

Чтобы добавить эту послойку нужно переписывать готовые алгоритмы, уже сейчас наблюдаю некоторые неверные решения, которые работают для ванильного Fallout, но уже некорректны со скриптовыми возможностями которые дает sfall, и не из-за того, что sfall что-то меняет, а из-за другой реализации здесь.
Просто тот кто писал код, мало знаком с этими самыми внуреностями fallout, как они работают, вследствии чего и не подстраивался под них.
Новый движок Fallout который бы просто читал ресурсы игры, можно было бы написать на каком-нибудь 2D/3D подходящем готовом кросс-платформенном движке, и не тратить уйму врени на это изобретение (если конечно не преследуется другой цели, или саморазвития в плане кодинга).
Как-то так :)

**Comment by alexeevdv** [comment]
> Новый движок Fallout который бы просто читал ресурсы игры, можно было бы написать/сделать на каком-нибудь 2D/3D подходящем готовом кросс-платформенном движке, и не тратить уйму времени на это изобретение (если конечно не преследуется другой цели, или саморазвития в плане кодинга).

В чем проблема? Возьми готовый движок и сделай, а мы наконец то поиграем в кроссплатформенный фолач

**Comment by phobos2077** [comment]
Не убедил. Я всё равно остаюсь при мнении что игровой движок должен быть корректно реализован с точки зрения игровых механик, с определенной расширяемостью. Ни в коем случае он не должен подстраиваться под прихоти старого движка. Следование хорошим практикам проектирования таким как SOLID и парадигмам, доказавшим свою пользу в геймдеве (таким как ECS), даст возможность расширения возможностей в любой момент, без "переписывания" чего-либо, а лишь добавляя.

В моём представлении "идеальная" архитектура должна выглядить примерно так:

[Ресурсы игры] - оригинальные ресурсы
[Прослойка поддержки ресурсов Fallout 1/2] - независимый слой, провайдер ресурсов для игры. Может читать ресурсы напрямую, как сделано сейчас, либо через оффлайн-конвертер ресурсов. Виртуальная машина скриптов входит в этот слой.
[Ядро игры] - сюда входят игровые механики, реализованные только с учётом нужного функционала игры. Механики могут расширяться без "переписывания" уже существующих механик (Open-closed principle).
[Интерфейс] - SDL, ввод-вывод, рендер, шейдеры, GUI и т.д. Также расширяется добавлением нужных классов и т.п.

**Comment by alexeevdv** [comment]
Да, все правильно говоришь. Но в текущей реинкарнации движка никаким SOLID и прочими радостями даже не пахнет. Я в любом месте пытаюсь изменить какую-нибудь мелочь и это тянет за собой пол движка ) С одной стороны интересно распутывать этот клубок и прокачивать навык рефакторинга, а с другой стороны демотивирует, т.к. требует кучу времени. Которого у меня нет от слова совсем

**Comment by phobos2077** [comment]
@alexeevdv как мне кажется главное достижение Falltergeist на текущий момент это как раз реализация второго слоя, т.е. загрузка ресурсов, интерпретация скриптов и конфигов. При должном желании кто-нибудь мог бы прикрутить это к любому другому движку, либо переписать всё что выше с нуля.

**Comment by phobos2077** [comment]
@alexeevdv @FakelsHub кто-нибудь из вас бывает в телеге или в discord? С удовольствием потрещал бы на тему Falltergeist, sfall и геймдева в целом.

**Comment by alexeevdv** [comment]
Я в дискорде почти всегда в наличии. [![Discord](https://img.shields.io/discord/401990446747877376.svg)](https://discord.gg/jxs6WRq)

**Comment by FakelsHub** [comment]
> В чем проблема? Возьми готовый движок и сделай,

Не, мне это неинтересно.
Меня устраивает текущий движок (кроме блятской палиты и кривого освещения спрайтов).

> Механики могут расширяться без "переписывания" уже существующих механик (Open-closed principle).

Зачем эти все эти высоко научные принципы, просто напишите движок. :)

**Comment by phobos2077** [comment]
> Зачем эти все эти высоко научные принципы, просто напишите движок. :)

Не, мне это неинтересно.
Меня устраивают текущие высоко научные принципы (кроме блятских проблем с архитектурой и отсутствующих механик).
