### ISSUE TITLE
Вопросы по коду движка.

### ISSUE THREAD

**Issue by FakelsHub** [falltergeist/falltergeist#602]
Есть ли какая-то необходимость хранить для каждого объекта их имена и описания? по сути одинаковые для всех объектов. Кажется, что это просто расход памяти.
```
object->setName(msg->message(proto->messageId())->text()
object->setDescription(msg->message(proto->messageId() + 1)->text());
```

**Comment by alexeevdv** [comment]
Нет необходимости. Будет переделано в будущем при переходе на компонентную систему
