### ISSUE TITLE
Removing timer from location causes the game to hang

### ISSUE THREAD

**Issue by AdamFx990** [falltergeist/falltergeist#608]
After selecting a character, the game hangs and the process needs to be killed manually.

EDIT: This seems to be issue on maps with rats.

### Expected Behavior

The game should work as it did before <a href="https://github.com/falltergeist/falltergeist/commit/31d3351198f1dda08bca6628aac678ffca703bc1">this commit.</a>

### Steps to Reproduce
1. Compile with g++
2. Press 'new game'
3. Select character & start game

### System
- **Falltergeist:** 31d3351198f1dda08bca6628aac678ffca703bc1
- **Operating System:** Fedora 30
- **Fallout:** Steam

### Notes

I've created a branch from this commit. I will create a pull request when I have a fix

**Comment by AdamFx990** [comment]
Fix is in pull request: #609

**Comment by vvbalashoff** [comment]
commit 0ceae6e5c3beb0a4da6c27b174622b45c8c83d4e

[INFO] [MESSAGE] You are once more in the village of your birth, Arroyo.
[INFO] [MESSAGE] You passed the trials of Arroyo.
[INFO] [MESSAGE] You gain 600 experience points.

game hangs, cpu usage 100%

**Comment by alexeevdv** [comment]
@vvbalashoff this should be fixed in #612 
can you check if it works for you?

**Comment by alexeevdv** [comment]
@AdamFx990 can you check if it fixes your issue too?

**Comment by vvbalashoff** [comment]
cadd5c307c14afc42ad7978d175fe1ccc018153c fix hangs
