### ISSUE TITLE
Health check

### ISSUE THREAD

**Issue by Nordsoft91** [falltergeist/falltergeist#689]
Last commit done 10 month ago. Project is dead?

**Comment by phobos2077** [comment]
While not the same thing (engine restoration vs engine remake), you might be interested in this project: https://github.com/alexbatalov/fallout2-ce
It got some momentum now and it's already fully playable.

**Comment by alexeevdv** [comment]
> Project is dead?

It depends on what you expect from it. Will it be ever finished or at least playable? I would say - no
