### ISSUE TITLE
Для чего нужен Falltergeist и развивается ли он?

### ISSUE THREAD

**Issue by QweSteR2221** [falltergeist/falltergeist#690]
Приветствую. Существует же sFall и CE. И даже есть FOnline. Технически зачем нужен Falltergeist? Или может мод какой на нём делается?

**Comment by M1sh2** [comment]
Если бы знал сколько этому проекту лет, и что одна история успеха не значит что все остальные проекты будут доведены до конца. Я думаю что подобный вопрос бы даже не был задан. Возможно уже нет времени на проект, возможно проект зашел в тупик, возможно какие то еще проблемы. Я знаю очень много печальных историй, когда проект забрасывался.

Initial commit - датируется аж Nov 24, 2012 чтоб было понятно. Именно по commit можно понять, развивается ли проект. Если появляются новые, добавляются новый код из pull request, значит проект развивается, понемногу.
https://github.com/falltergeist/falltergeist/commit/11c3f0a3a03e8e0720027bccbc469316e71e9570

https://osgameclones.com/ - есть вот такой замечательный сайт по открытым проектам, можно посмотреть что есть которые никогда не будут доведены до конца, как пример какой-нибудь ремейк space station 13 с меткой "halted", когда то считалось что есть проклятье из-за которого никогда не будет ремейка. Игра слишком разнообразная, слишком много кода придется написать для всех систем.

**Comment by phobos2077** [comment]
С sfall сравнивать вообще некорректно. В целом все 3 проекта разные и друг друга не дублируют:

- sfall расширяет старый движок правкой машинного кода в памяти.
- CE реверсит старый движок целиком 1 в 1, по сути ближе к sfall но без возни с машинным кодом.
- Falltergeist это новый движок. Как например OpenXCom или OpenTTD.

**Comment by alexeevdv** [comment]
Приветствую.

> Для чего нужен Falltergeist

Этот проект начинался как хобби. Цель - разобраться с устройством движка оригинальной игры и получить опыт разработки на С++

>Развивается ли он?

Как написали выше - можно посмотреть по истории коммитов. У меня больше нет времени заниматься этим проектом. Совсем другие приоритеты теперь. Хотя какой-никакой интерес к теме fallout и остался.

На текущий момент могу сказать что в проекте больше нет никакого смысла. Если хочется получить конкретный результат, то лучше взять готовую платформу(движок) и дописать к ней плагины для работы с ресурсами Fallout. Нет никакой нужды тратить время на низкоуровневые вещи вроде графики, ввода, звука и т.д. Я этим занимался исключительно потому что был интерес и время во всём этом разобраться

Так же нет никакой нужды в falltergeist как в источнике знаний по устройству движка оригинальной игры, т.к. проделана огромная работа в CE. Можно посмотреть как оно работает на самом деле, а не как получилось сделать в рамках этого проекта

Так что повторюсь еще раз - этот проект just for fun

**Comment by QweSteR2221** [comment]
> Так что повторюсь еще раз - этот проект just for fun

Ещё 2 вопроса. Просто разбираюсь в истории движков Ф2.

1. Мододел Jordan имел какое отношение к Falltergeist?
2. Т.е. разработка Falltergeist никак не связана с запретом Bethesda использовать моддерам их движок?

**Comment by alexeevdv** [comment]
1. Не знаю такого. Никогда не интересовался моддерством фаллаута, поэтому ни с кем не знаком
2. Первый раз слышу про запреты Bethesda, поэтому не связана

Мне просто нравится фаллаут и вдохновляясь работой проделанной на то время openxcom(еще одна из моих любимых игр) я решил попробовать свои силы в разработке движка

**Comment by QweSteR2221** [comment]
ясно. спс. на этом вопросов больше не имею.
значит и никакой глобальной цели не было.

1. он первым предпринял попытку перевести Ф1 на двиг Ф1. потом отказался от идеи. и сослался, что вот есть этот двиг. но то было очень-очень давно.
2. да. было такое. я уже это теперь точно знаю., есть и публикации в инете. но было найдено решение. и моддинг ф2 не останавливался.
